sudo: required
services: docker

before_install:
  - docker build -t barabis/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run barabis/react-test npm test -- --coverage

after_success:
  - docker build -t barabis/multi-client ./client
  - docker build -t barabis/multi-server ./server
  - docker build -t barabis/multi-worker ./worker
  - docker build -t barabis/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push barabis/multi-client
  - docker push barabis/multi-server
  - docker push barabis/multi-worker
  - docker push barabis/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-multi'
  env: 'DockerMulti-env'
  bucket_name: 'elasticbeanstalk-us-east-1-487429313413'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
